// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0p3ZXOrGxNQe-S69s711gYWIIooUetlg',
    appId: '1:29392343178:web:b0440cda9317c058dd9d73',
    messagingSenderId: '29392343178',
    projectId: 'tradingblitz-600ad',
    authDomain: 'tradingblitz-600ad.firebaseapp.com',
    storageBucket: 'tradingblitz-600ad.firebasestorage.app',
    measurementId: 'G-7FVJE0LQD8',
  );


  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCarExjkVmLm9EDLxLdTsow634NJ9OvSuY',
    appId: '1:29392343178:android:95434108de894875dd9d73',
    messagingSenderId: '29392343178',
    projectId: 'tradingblitz-600ad',
    storageBucket: 'tradingblitz-600ad.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFq97quiyqz2uEWA32CpAMLkj7jNh3jK0',
    appId: '1:29392343178:ios:c44bf4bda6771cdbdd9d73',
    messagingSenderId: '29392343178',
    projectId: 'tradingblitz-600ad',
    storageBucket: 'tradingblitz-600ad.firebasestorage.app',
    androidClientId: '29392343178-qum9mt1ephlb5l2veikc2teft1qr0c15.apps.googleusercontent.com',
    iosClientId: '29392343178-fnmkmmvdridlt6971kqn2m2v7d0g651b.apps.googleusercontent.com',
    iosBundleId: 'com.tradingblitz.mobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFq97quiyqz2uEWA32CpAMLkj7jNh3jK0',
    appId: '1:29392343178:ios:c44bf4bda6771cdbdd9d73',
    messagingSenderId: '29392343178',
    projectId: 'tradingblitz-600ad',
    storageBucket: 'tradingblitz-600ad.firebasestorage.app',
    androidClientId: '29392343178-qum9mt1ephlb5l2veikc2teft1qr0c15.apps.googleusercontent.com',
    iosClientId: '29392343178-fnmkmmvdridlt6971kqn2m2v7d0g651b.apps.googleusercontent.com',
    iosBundleId: 'com.tradingblitz.mobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA0p3ZXOrGxNQe-S69s711gYWIIooUetlg',
    appId: '1:29392343178:web:6257b3c5219ca8a7dd9d73',
    messagingSenderId: '29392343178',
    projectId: 'tradingblitz-600ad',
    authDomain: 'tradingblitz-600ad.firebaseapp.com',
    storageBucket: 'tradingblitz-600ad.firebasestorage.app',
    measurementId: 'G-5XXTZDRZ5Z',
  );

}